service: widget-authorizer

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: sls.workshop.sketchdev.io
    staging: staging-sls.workshop.sketchdev.io
    dev: dev-sls.workshop.sketchdev.io

functions:
  authorizer:
    handler: index.handler
    environment:
      AUDIENCE: ${env:AUDIENCE, https://${self:custom.domains.${self:custom.stage}}}
      JWKS_URI: ${env:JWKS_URI, "https://sketchdev-io.auth0.com/.well-known/jwks.json"}
      TOKEN_ISSUER: ${env:TOKEN_ISSUER, "https://sketchdev-io.auth0.com/"}
